import{a as m,S as q,i as n}from"./assets/vendor-C9jUDwr_.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))f(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&f(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function f(t){if(t.ep)return;t.ep=!0;const a=o(t);fetch(t.href,a)}})();m.defaults.baseURL="https://pixabay.com/api/";async function p(s,e=1){return(await m.get("",{params:{key:"52056130-db9fbcb72f3bb5afb21255a47",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}const y=document.querySelector(".gallery"),r=document.querySelector(".loader"),h=document.querySelector(".load-more-btn");let d=null;function g(s){const e=s.map(o=>`
    <div class="card gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" class="gallery-images">
      </a>
      <div class="info">
        <p class="name">Likes<span class="value">${o.likes}</span></p>
        <p class="name">Views<span class="value">${o.views}</span></p>
        <p class="name">Comments<span class="value">${o.comments}</span></p>
        <p class="name">Downloads<span class="value">${o.downloads}</span></p>
      </div>
    </div>
  `).join("");y.insertAdjacentHTML("beforeend",e),d?d.refresh():d=new q(".gallery a",{captionsData:"alt",captionDelay:250})}function M(){y.innerHTML=""}function L(s=!0){r.classList.add("is-visible"),s?(r.classList.add("initial"),r.classList.remove("load-more")):(r.classList.add("load-more"),r.classList.remove("initial"))}function b(){r.classList.remove("is-visible","initial","load-more")}function v(){h.style.display="block"}function w(){h.style.display="none"}const $=document.querySelector(".search-form"),B=document.querySelector(".load-more-btn");let i="",l=1,u=0;const S=15;$.addEventListener("submit",async s=>{if(s.preventDefault(),i=s.target.elements.searchQuery.value.trim(),!i){n.warning({message:"Please enter a search term"});return}l=1,M(),w(),L(!0);try{const e=await p(i,l);if(u=e.totalHits,!e.hits.length){n.error({message:"No images found"});return}g(e.hits),u>S&&v()}catch{n.error({message:"Something went wrong"})}finally{b()}});B.addEventListener("click",async()=>{l+=1,w(),L(!1);try{const s=await p(i,l);g(s.hits);const e=Math.ceil(u/S);l<e?v():n.info({message:"We're sorry, but you've reached the end of search results."}),P()}catch{n.error({message:"Something went wrong"})}finally{b()}});function P(){const s=document.querySelector(".gallery-item");if(s){const{height:e}=s.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
